title: <p align="center"> Khang Truong </p>
logo: /assets/img/me.jpg

description:
  <p align="center">
  <a href="docs/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/khangtruong97/">LinkedIn</a> |
  <a href="https://github.com/khang-nguyen-truong">GitHub</a>
  
  <br>
  I'm working on Data Science and Data Visualization
  <br>
  </p>



theme: jekyll-theme-minimal
